/// <reference types="vite/client" />
declare module '@components/*'
declare module '@views/*'
declare module '@store/*'
declare module '@utils/*'
declare module '@router/*'
declare module '@assets/*'
declare module '@mock/*'
declare module '@services/*'
declare module '@types/*'
declare module '@commons/*'
declare module '@/*'
